spring:
  application:
    name: app-money-track
  datasource:
    url: jdbc:postgresql://localhost:5433/db-money-track
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 186575724653-juh6l1oidgit5n63kh834rsv84sv4ls2.apps.googleusercontent.com
            client-secret: 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
            scope:
            - openid
            - profile
            - email
          github:
            client-id: Ov23lisWdEEGHFQPtKaC
            client-secret: 32f61ab039c558cf6345b5db0d7a7b84689065b6
            scope:
            - read:user
            - user:email
server:
  servlet:
    context-path: /api/money-track
  port: 8080